### PR TITLE
Configure the project for global installation and CLI run

### PR DESCRIPTION
**Pull request by MytsV**
# Purpose

To make the app globally installable and available as a CLI command. We must be able to run it as
```
todolor
```
after installation.

# Summary

Add bin entry to package.json to indicate which JS file will be executed on running todolor. Make index.js executable via a shebang line, indicating NodeJS interpreter. 

# Other information

To install the app locally at the current stage, please, use
```
npm link
```
as root.

### CODE REVIEW

**Comment by MytsV** [comment]
@svitbar please, test it locally (you're switched to Windows, aren't you?) and inform me of the results

**Review by svitbar — COMMENTED** [review]
image
I have a problem with running the app.

**Comment by MytsV** [comment]
Have you tried this [solution](https://ru.stackoverflow.com/questions/935212/powershell-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B5%D0%B2-%D0%BE%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%BE-%D0%B2-%D1%8D%D1%82%D0%BE%D0%B9-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5)?

> image I have a problem with running the app.

**Review by svitbar — APPROVED** [review]
The solution succeeded! Thank you!

**Pull request merged**
